name: Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # ← ここは公開したいフォルダ（例: dist/docs に変更しても可）

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
